### ISSUE TITLE
Slow firing sounds

### ISSUE THREAD

**Issue by deurk** [deurk/mvdsv#15]
> ping up, fire sng - it sounds like you're firing slower
> whats actually happening is that the packets arrive at the same time, so the sound over-writes itself and you only hear every second sound
> doesn't happen on FTE

**Comment by meag** [comment]
Spent a bit of time on this the other day - the issue is with reliable sound feature in mvdsv, and the resulting packets on high-ping.

A high-ping player won't confirm the reliable packet is received quickly enough, so the second sng firing sound is added to the same packet, and the sound can effectively be lost client-side.

Have created https://github.com/ezQuake/ezquake-source/issues/230 for ezquake to handle this situation better, at very least making 'reliable sounds' a more obvious feature (it also broke ezquake's pickup detection, so lots of players turn it off).
